CONFIG = {
    "dataset_name": "Anthropic/hh-rlhf",
    "dataset_config": None,
    "model_name": "Qwen/Qwen2.5-0.5B-Instruct",
    "output_dir": "outputs/reward_model_hh_rlhf",
    "max_length": 256,
    "epochs": 1,
    "learning_rate": 2e-5,
    "weight_decay": 0.01,
    "batch_size": 1,
    "gradient_accumulation_steps": 8,
    "mixed_precision": True,
    "eval_ratio": 0.02,
    "max_train_samples": 10000,
    "max_eval_samples": None,
    "seed": 42,
}
